### ISSUE TITLE
Should possibly split long lines

### ISSUE THREAD

**Issue by anderspitman** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#152]
Long lines should maybe be split at a certain maximum number of characters (80, 120, etc) in the interest of handling diffs easier. Beyond a certain number of characters it appears that github doesn't show you exactly what changed in a line.

**Comment by gregcaporaso** [comment]
I agree that this is annoying, but it also would make writing really annoying because I'd have to manually break/unbreak lines. Also, I sometimes edit in Jupyter and sometimes in Atom, and in Jupyter I don't have a way to know how many characters are on a line. Going to close this one - hoping GitHub just fixes the diffs someday...
