### ISSUE TITLE
get IAB on pypi

### ISSUE THREAD

**Issue by gregcaporaso** [gregcaporaso/An-Introduction-To-Applied-Bioinformatics#95]

**Comment by jairideout** [comment]
I don't think IAB makes sense on PyPI because the IAB library code is moving out of the project so there won't be anything to install at that point. Even if you pip-installed IAB from PyPI, readers will still need to download the notebooks somehow (e.g., `git clone`) to read and interact with the book.

@gregcaporaso is this okay to close?

**Comment by gregcaporaso** [comment]
Yep, I think you're right.
